repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^\.github/workflows/.*$
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
    exclude: ^(src/\{project\}|tests)/.*$
  - id: debug-statements
    exclude: ^(src/\{project\}|tests)/.*$

- repo: local
  hooks:
  - id: ruff-format
    name: ruff format
    entry: make format
    language: system
    types: [ python ]
    pass_filenames: false
  - id: ruff-lint
    name: ruff lint
    entry: make lint
    language: system
    types: [ python ]
    pass_filenames: false
  - id: mypy
    name: mypy
    entry: make type-check
    language: system
    types: [ python ]
    pass_filenames: false
  - id: bandit
    name: bandit
    entry: make security-check
    language: system
    types: [ python ]
    pass_filenames: false
  - id: gitlint
    name: gitlint
    entry: make commit-check
    language: system
    stages: [ commit-msg ]
    always_run: true
    pass_filenames: false

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.2
  hooks:
  - id: gitleaks
